lol=msgbox("This Is A Bomb. It will Explode.",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 10 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 9 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 8 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 7 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 6 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 5 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 4 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 3 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 2 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 1 Clicks",32,"This is a Bomb.")
lol=msgbox("LAST CHANCE!",32,"This is a Bomb.")
lol=msgbox("Goodbye!",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("huh?",32,"This is a Bomb.")
lol=msgbox("it's supposed to blow up by now",32,"This is a Bomb.")
lol=msgbox("OH!",32,"This is a Bomb.")
lol=msgbox("i figured out what's wrong",32,"This is a Bomb.")
lol=msgbox("Hang on...",32,"This is a Bomb.")
lol=msgbox("just add some wires, connect this all together...",32,"This is a Bomb.")
lol=msgbox("annnndd?",32,"This is a Bomb.")
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.Run "C:\WINDOWS\system32\shutdown.exe -r -t 20"
lol=msgbox("i think that worked",32,"This is a Bomb.")
lol=msgbox("yep, see ya!",32,"This is a Bomb.")



