lol=msgbox("This Is A Bomb. It will Explode.",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 10 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 9 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 8 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 7 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 6 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 5 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 4 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 3 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 2 Clicks",32,"This is a Bomb.")
lol=msgbox("Time Until Bomb Explodes: 1 Clicks",32,"This is a Bomb.")
lol=msgbox("LAST CHANCE!",32,"This is a Bomb.")
lol=msgbox("Goodbye!",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("...",32,"This is a Bomb.")
lol=msgbox("huh?",32,"This is a Bomb.")
lol=msgbox("it's supposed to blow up by now",32,"This is a Bomb.")
lol=msgbox("well, this entire time...",32,"This is a Bomb.")
lol=msgbox("You've just been Pranked!!! LMAOOOOOOOOOO!! XDXD L=Ratio BOZO.",32,"This NOT is a Bomb.")
lol=msgbox("A simple vbs script by GamerzSocks. My GitHub: github.com/gamerzsocks. 2023. V.1.1",32,"This NOT is a Bomb.")



